### ISSUE TITLE
[V3] Timeline Commands Todo List

### ISSUE THREAD

**Issue by rmevans9** [infinitered/reactotron#863]
Timeline is coming together. We only have a few top level things to work out (first checklist) and commands to plow through (second checklist). I am adding it all here so we can track what all is left. Please let me know in the comments if I am missing anything.

- [x] Commands need `toolbar` to be implemented to provide the ability to do actions
- [ ] "Clear Commands" button needs added (in v2 this is in the "title bar" which isn't implemented yet)
- [x] It appears we are re-rendering every command anytime a new command comes in. This could be bad.
- [ ] Search
- [ ] Filtering

If `Shell Created` is checked that means we have the command setup but we need to go in and get the data to look right. `Styling` means the data is on there and correct

- Client Intro Command (AKA Connection Command)
  - [x] Shell Created
  - [x] Styling
- API Response Command
  - [x] Shell Created
  - [ ] Styling
- Async Storage Mutation Command
  - [x] Shell Created
  - [ ] Styling
- Async Storage Values Command
  - [x] Shell Created
  - [ ] Styling
- Benchmark Report Command
  - [x] Shell Created
  - [ ] Styling
- Display Command
  - [x] Shell Created
  - [ ] Styling
- Image Command
  - [x] Shell Created
  - [ ] Styling
- Log Command
  - [x] Shell Created
  - [ ] Styling
- Saga Task Complete Command
  - [x] Shell Created
  - [ ] Styling
- State Action Complete Command
  - [x] Shell Created
  - [ ] Styling
- State Keys Response Command
  - [x] Shell Created
  - [ ] Styling
- State Values Change Command
  - [x] Shell Created
  - [ ] Styling
- State Values Response Command
  - [x] Shell Created
  - [ ] Styling
- Unknown Command
  Is this thing even used? Probably should research it.
  - [ ] Shell Created
  - [ ] Styling
